site_name: 中文跨性别文档
site_url: https://docs.transzh.org
theme:
  name: material
  custom_dir: overrides
  features:
    - announce.dismiss
  language: zh
  logo: static/icon.png
  favicon: static/icon.png
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: 切换亮色模式
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: 切换深色模式
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: 跟随系统
nav:
  - 分类索引: index.md
  - 贡献指南: contribute.md
  - 友情链接: links.md
markdown_extensions:
  - attr_list
extra:
  generator: false
copyright: 本站所收集的内容版权归原著作权人所有，本站仅做二次摘抄、修订及整理，不代表原版权方的立场或观点。
extra_css:
  - stylesheets/extra.css